### 
GET http://localhost:8500/services

### 
GET http://localhost:8500/config

### msg1
POST http://localhost:8080/transaction
Content-Type: application/json

{
    "user_Id": "msg1",
    "amount": 1.00
}

### msg2
POST http://localhost:8080/transaction
Content-Type: application/json

{
    "user_Id": "msg2",
    "amount": 2.00
}

### msg3
POST http://localhost:8080/transaction
Content-Type: application/json

{
    "user_Id": "msg3",
    "amount": 3.00
}

### msg4
POST http://localhost:8080/transaction
Content-Type: application/json

{
    "user_Id": "msg4",
    "amount": 4.00
}

### msg5
POST http://localhost:8080/transaction
Content-Type: application/json

{
    "user_Id": "msg5",
    "amount": 5.00
}

### msg6
POST http://localhost:8080/transaction
Content-Type: application/json

{
    "user_Id": "msg6",
    "amount": 6.00
}

### msg7
POST http://localhost:8080/transaction
Content-Type: application/json

{
    "user_Id": "msg7",
    "amount": 7.00
}

### msg8
POST http://localhost:8080/transaction
Content-Type: application/json

{
    "user_Id": "msg8",
    "amount": 8.00
}

### msg9
POST http://localhost:8080/transaction
Content-Type: application/json

{
    "user_Id": "msg9",
    "amount": 9.00
}

### msg10
POST http://localhost:8080/transaction
Content-Type: application/json

{
    "user_Id": "msg10",
    "amount": 10.00
}

### 
GET http://localhost:8080/user/msg1

### 
GET http://localhost:8080/user/msg10

### 
GET http://localhost:8080/accounts

### 
GET http://localhost:8080/metrics


### msg11 (
POST http://localhost:8080/transaction
Content-Type: application/json

{
    "user_Id": "msg1",
    "amount": 50.00
}

### msg12
POST http://localhost:8080/transaction
Content-Type: application/json

{
    "user_Id": "msg2",
    "amount": 100.00
}

### 
GET http://localhost:8080/user/msg1

### 
GET http://localhost:8080/user/msg2
