### health check
GET http://localhost:8080/health

### msg1
POST http://localhost:8080/transaction
Content-Type: application/json

{
    "user_Id": "msg1",
    "amount": 1.00
}

### msg2
POST http://localhost:8080/transaction
Content-Type: application/json

{
    "user_Id": "msg2",
    "amount": 2.00
}

### msg3
POST http://localhost:8080/transaction
Content-Type: application/json

{
    "user_Id": "msg3",
    "amount": 3.00
}

### msg4
POST http://localhost:8080/transaction
Content-Type: application/json

{
    "user_Id": "msg4",
    "amount": 4.00
}

### msg5
POST http://localhost:8080/transaction
Content-Type: application/json

{
    "user_Id": "msg5",
    "amount": 5.00
}

### get details and transactions for first user
GET http://localhost:8080/user/msg1

### get balances of all accounts
GET http://localhost:8080/accounts

### view performance metrics 
GET http://localhost:8080/metrics

### reset performance metrics 
POST http://localhost:8080/metrics/reset

### large transaction to check balance updates
POST http://localhost:8080/transaction
Content-Type: application/json

{
    "user_Id": "msg1",
    "amount": 50.00
}

### another large transaction
POST http://localhost:8080/transaction
Content-Type: application/json

{
    "user_Id": "msg2",
    "amount": 100.00
}