apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-deployment
  namespace: micro-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: counter-service
  template:
    metadata:
      labels:
        app: counter-service
    spec:
      containers:
        - name: counter-service
          image: counter-image:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: microservices-config
          # Додаємо пароль та URL до бази з Secret
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: microservices-secrets
                  key: DATABASE_URL
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: counter-service
  namespace: micro-lab
spec:
  selector:
    app: counter-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000