apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-pvc
  namespace: micro-lab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: micro-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_DB
              value: "counterdb"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: microservices-secrets
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: pg-storage
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["sh", "-c", "pg_isready -U postgres -d counterdb"]
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ["sh", "-c", "pg_isready -U postgres -d counterdb"]
            initialDelaySeconds: 15
            periodSeconds: 10
      volumes:
        - name: pg-storage
          persistentVolumeClaim:
            claimName: postgres-data-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-db
  namespace: micro-lab
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432