apiVersion: v1
kind: Secret
metadata:
  name: microservices-secrets
  namespace: micro-lab
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:postgres@postgres-db:5432/counterdb"
  POSTGRES_PASSWORD: "postgres"